### ISSUE TITLE
Getting error on npm run generate

### ISSUE THREAD

**Issue by Almusamim** [bskimball/nuxtober#2]
When I run npm run generate I get this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Hadi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'generate' ]
2 info using npm@6.4.1
3 info using node@v8.11.3
4 verbose run-script [ 'pregenerate', 'generate', 'postgenerate' ]
5 info lifecycle nuxtober@1.0.0~pregenerate: nuxtober@1.0.0
6 info lifecycle nuxtober@1.0.0~generate: nuxtober@1.0.0
7 verbose lifecycle nuxtober@1.0.0~generate: unsafe-perm in lifecycle true
8 verbose lifecycle nuxtober@1.0.0~generate: PATH: C:\Users\Hadi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\wamp\www\october\themes\nuxtOct\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\OpenSSL\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Ruby24-x64\bin;C:\Users\Hadi\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Hadi\AppData\Local\Yarn\bin;D:\wamp\bin\php\php7.1.9;C:\Users\Hadi\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Sublime Text 3;D:\wamp\bin\mysql\mysql5.7.19\bin;C:\Users\Hadi\AppData\Local\hyper\app-2.0.0\resources\bin;C:\Program Files\MongoDB\Server\4.0\bin;C:\Users\Hadi\AppData\Roaming\npm
9 verbose lifecycle nuxtober@1.0.0~generate: CWD: D:\wamp\www\october\themes\nuxtOct
10 silly lifecycle nuxtober@1.0.0~generate: Args: [ '/d /s /c', 'nuxt generate' ]
11 silly lifecycle nuxtober@1.0.0~generate: Returned: code: 1  signal: null
12 info lifecycle nuxtober@1.0.0~generate: Failed to exec generate script
13 verbose stack Error: nuxtober@1.0.0 generate: `nuxt generate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Hadi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Hadi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nuxtober@1.0.0
15 verbose cwd D:\wamp\www\october\themes\nuxtOct
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hadi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate"
18 verbose node v8.11.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error nuxtober@1.0.0 generate: `nuxt generate`
22 error Exit status 1
23 error Failed at the nuxtober@1.0.0 generate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by bskimball** [comment]
Did you npm install? Looks like it doesn't see nuxt.

**Comment by bskimball** [comment]
I'll look at this a little later

**Comment by Almusamim** [comment]
@bskimball sure :)
the files get generated but I keep having this error about missing .nojekyll file

**Comment by bskimball** [comment]
This is strange because I get the same error when I clone this repo, but in the environment, where I originally created this repo (my local repo), the .nojekyll file is generated just fine.

The .nojekyll file isn't even really needed in this application of nuxt. I originally thought it may have something to do with it beginning with a "." but the .nuxt folder is being generated just fine.

**Comment by Almusamim** [comment]
It must be when you run the generate command and all the files in the pages directory where .nojekyll is located get deleted so we must regenerate .nojekyll  again somehow or prevent it from getting deleted? 

searching for nojekyll in Nuxt repository gives me this
https://github.com/nuxt/nuxt.js/blob/226b90d4aee8b30f035cd0ec189d99d22dba5ec2/lib/builder/generator.js#L173-L179

**Comment by bskimball** [comment]
This should be resolved with the latest version. I had to run some of the hooks async.

**Comment by Almusamim** [comment]
tested it today the issue remains

**Comment by bskimball** [comment]
I updated to Nuxt 2.0 recently, I will have to test some things.

**Comment by bskimball** [comment]
@Almusamim give it a try with the latest. I will leave the issue open as I have not done much testing.

**Comment by Almusamim** [comment]
no more annoying  .nojekyll missing error

**Comment by bskimball** [comment]
Cool. I'll close the issue
